"""make unnecessary fields nullable

Revision ID: 6f317c1246aa
Revises: a4045bb1ccf2
Create Date: 2026-09-20 20:51:27.116455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f317c1246aa'
down_revision: Union[str, Sequence[str], None] = 'a4045bb1ccf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_factors', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('risk_factors', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('risk_factors', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('risk_factors', 'video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risk_factors', 'video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('risk_factors', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('risk_factors', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('risk_factors', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
